source 'http://rubygems.org'
#source 'https://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'
gem 'mysql2'

gem 'execjs'
gem 'therubyracer'
#gem 'rack' , '1.4.5'
gem 'json'

# Deploy with Capistrano
gem 'capistrano'
gem 'nokogiri', '~> 1.5.10'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '3.1.4'
  gem 'uglifier'
  gem 'compass', '0.12.alpha.4'
  gem 'compass-h5bp'
end

gem 'haml-rails' # Optional - to generate haml

gem 'jquery-rails', '1.0.19' #must be fixed because current version of multiselect widget doesn't work with jquery version >= 1.8.0
gem 'html5-rails', '0.0.4'
gem 'gdata', :git => 'https://github.com/agentrock/gdata.git'
gem "iconv", "~> 1.0.3"
gem 'sprockets'
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

gem 'devise', '2.0.0'

gem "omniauth-facebook", '~>1.4.1'
gem "omniauth-twitter", '~>0.0.12'
gem "omniauth-google-oauth2", '~>0.1.13'

gem "koala", '~>1.6.0'
gem "fb_graph", '~>2.5.9'
gem 'twitter', '~>4.0.0'


gem "ancestry", '~>1.3.0 '
gem 'simple_form', '~>2.0'
gem 'paperclip', '~>2.7'
gem 'client_side_validations', '3.1.4'
gem 'will_paginate', '~>3.0.3'
gem 'browser', '~>0.1.5'

gem 'geokit-rails3', '~>0.1.5'

gem "recaptcha", :require => "recaptcha/rails"

gem 'whenever', :require => false
gem "activemerchant", '~>1.29.0'
gem "paypal-sdk-merchant"
gem 'paypal-sdk-adaptivepayments'
gem "hpricot", "~> 0.8.6"
gem 'money', '~>5.0.0'
gem 'contacts', '~>1.2.4'

gem 'fastercsv','~>1.5.5'
gem 'cmess', '~>0.3.1'

gem "grape", "0.2.1"

gem 'httparty', '~>0.10.0'
gem 'delayed_job_active_record', '~>0.3.2'
gem "daemons", '~>1.1.4'
gem "rake-progressbar", '~>0.0.5'

gem 'useragent'

gem 'typhoeus'
gem 'tire'
gem 'roo', '1.10.3', :require => false
gem 'rubyzip', '< 1.0.0', :require => false
gem 'google_places'
gem 'foursquare2'
gem 'twilio-ruby'
gem 'orm_adapter'
#gem 'elasticsearch'
gem 'rails3-jquery-autocomplete'

group :development, :test do
  gem 'thin'
  gem 'machinist', '~>2.0'
  gem 'faker', '~>1.1.1'
  gem 'rails-dev-tweaks', '~> 0.6.1'
#  gem 'rails-dev-tweaks', '~> 1.1'
end
gem "httpclient", '~>2.5.3.1'
